[package]
name = "cache-mii"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12.12", features = ["json"] }
bytes = "1"